### ISSUE TITLE
INFOGRAFIA_HILOS

### ISSUE THREAD

**Issue by Antonia2410** [SistemasTecTlaxiaco/infografia-de-hilos-Antonia2410#2]
[HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Antonia2410/files/15066230/HILOS.pdf)

**Comment by AricelCastro** [comment]
nuestro equipo le da una calificación de 18.5/20 falto aplicacion

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
